### PR TITLE
Add a rather* primitive multi-file support, old chap

### PR DESCRIPTION
**Pull request by SquidDev**
So my editor decides that "very" is a weasel word, so here we are.

### CODE REVIEW

**Comment by zardyh** [comment]
I feel terrible saying this, but, surprisingly, it looks good to me. Are we sure it works, though?

**Comment by SquidDev** [comment]
> Are we sure it works, though?

I tested a couple of basic multi-file "projects" and it all seemed to work. Not that that's a guarantee though.

**Comment by SquidDev** [comment]
Too late now!

**Comment by zardyh** [comment]
Ah, the Amulet way of doing things.

**Pull request merged**
