### PR TITLE
Core Lint

### PR DESCRIPTION
**Pull request by SquidDev**
I still need to do casts (and thus coercions) and patterns, but I'm slightly less sure about how to do them.

### CODE REVIEW

**Comment by zardyh** [comment]
Eugh. This will need lots of fixing with Dependent Amulet :/

**Comment by zardyh** [comment]
A TODO (@SquidDev): Record coercions are not working out properly. What do we do about those?

**Comment by zardyh** [comment]
Removing the WIP status as the full optimiser pipeline preserves typing, and this is ready for merge.

**Comment by zardyh** [comment]
@SquidDev Look good?

**Comment by SquidDev** [comment]
Who else is looking forward to round 2 of this in a couple of weeks?

**Pull request merged**
